# config context path to "/" by setting an empty string
server:
  contextPath: /skhu

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;databaseName=dbp1;
    username: sa
    password: test123
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# jwt 속성
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

# 서버 로그 찍기
#logging:
#  level:
#      org.hibernate:
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: TRACE
#    org.springframework:
#      security: DEBUG
